# Generated by Django 4.0.4 on 2022-10-11 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0023_purchasebill_balance_due'),
    ]

    operations = [
        migrations.CreateModel(
            name='purchasepayment',
            fields=[
                ('pymntid', models.AutoField(primary_key=True, serialize=False, verbose_name='bid')),
                ('reference', models.IntegerField(default=1000)),
                ('vendor', models.CharField(max_length=100)),
                ('paymentdate', models.DateField(null=True)),
                ('paymentmethod', models.CharField(max_length=100, null=True)),
                ('depositeto', models.CharField(max_length=100)),
                ('billdate', models.DateField(null=True)),
                ('billno', models.CharField(max_length=100, null=True)),
                ('billamount', models.CharField(max_length=100, null=True)),
                ('amountdue', models.CharField(max_length=100, null=True)),
                ('payment', models.CharField(max_length=100, null=True)),
                ('paymentamount', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
