# Generated by Django 4.0.4 on 2022-10-12 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0024_purchasepayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='purchasepayment1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billdate', models.DateField(null=True)),
                ('billno', models.CharField(max_length=100, null=True)),
                ('billamount', models.CharField(max_length=100, null=True)),
                ('amountdue', models.CharField(max_length=100, null=True)),
                ('payment', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='purchasepayment',
            name='amountdue',
        ),
        migrations.RemoveField(
            model_name='purchasepayment',
            name='billamount',
        ),
        migrations.RemoveField(
            model_name='purchasepayment',
            name='billdate',
        ),
        migrations.RemoveField(
            model_name='purchasepayment',
            name='billno',
        ),
        migrations.RemoveField(
            model_name='purchasepayment',
            name='payment',
        ),
    ]
