# Generated by Django 4.0.4 on 2022-10-12 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0025_purchasepayment1_remove_purchasepayment_amountdue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasepayment1',
            name='pymnt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.purchasepayment'),
        ),
    ]
